version: "2.4"

services:
  school:
    image: school:1.0.6
    mem_limit: 300m
    ports:
    - "8080:8080"
    environment:
      - "URL_DATABASE=${DATABASE}"
      - "RABBITMQ_HOST=${RABBITMQ_HOST}"
      - "RABBITMQ_USERNAME=${RABBITMQ_USERNAME}"
      - "RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}"
      - "RABBITMQ_PORT=${RABBITMQ_PORT}"

networks:
  default:
    external:
      name: software-rabbit